# -*- coding: utf-8 -*-
"""sentiment analyzer  using Ollama.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Npj4qPTK1KXetFlmIDQDcei8aoB6iO4_

# Data Collection

Primero, procedemos a instalar las librerias
"""

!pip install requests
!pip install GoogleNews

"""Configuramos la API de google news para recolectar noticias sobre la ciudad de San Andres durante los meses de junio y julio, los cuales osn temporada alta de vacaciones"""

from GoogleNews import GoogleNews
import pandas as pd

googlenews = GoogleNews(lang='es', region='CO')

googlenews.set_time_range('06/03/2024', '07/04/2024')

googlenews.search('turismo "San Andrés Islas" Colombia')

results = googlenews.result()

df = pd.DataFrame(results)

for index, row in df.iterrows():
    print(f"Titulo: {row['title']}")
    print(f"Medio: {row['media']}")
    print(f"Descripción: {row['desc']}")
    print(f"Fecha: {row['date']}")
    print(f"URL: {row['link']}")
    print('-'*50)

df.to_csv('noticias_turismo_san_andres.csv', index=False)

"""A partir del dataframe df, donde se encuentra la informacion recolectada, creamos una serie de pandas con la descripcion de las noticias

# Data Preparation
"""

contents = df["desc"]
print(contents)

!pip install ydata-profiling==4.7.0 -q

# Realizamos un analisis exploratorio de los datos
from ydata_profiling import ProfileReport
profile = ProfileReport(df)
profile

"""# Modelling

Se pretende desarrollar un modelo de machine learning que pueda leer las noticias recolectadas sobre La ciudad de San Andres, y nos arroje los 3 principales sentimientos que componen cada noticia, con el fin de determinar el potencial de turismo que tiene dicha ciudad, el modelo se basado en el LLM Ollama, el cual tiene como gran ventaja su potencia y que es open source
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install langchain_community -q
# Instalemos Ollama en Colab
!curl -fsSL https://ollama.com/install.sh | sh
# Installemos una terminal en Colab para ejecutar Ollama
!pip install colab-xterm
# %load_ext colabxterm

# Commented out IPython magic to ensure Python compatibility.
# %xterm
#run in terminal
#ollama serve

!ollama pull phi3:14b-medium-4k-instruct-q6_K

# Definamos la cadena con langchain
from operator import itemgetter
from langchain_community.chat_models import ChatOllama
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate

prompt = ChatPromptTemplate.from_messages([
  ("system", "You are a sentiment analyzer for news articles.\n"
  "Read the following news article and determine 3 most important emotions,dont explain the emotion, only put the word for them, dont put a period after the last emotion"),

  ("human", "Analyze the following news article:\n\"{noticia}\"")])
#"Read the following news article and describe the emotions and sentiments you identify in the text."),
#("system","Read the following news article and determine if the new is positive, negativo or neutral for the tourism, dont explain why, only select the word that apply."),
model = "phi3:14b-medium-4k-instruct-q6_K"
# model = "gemma2:9b-instruct-q8_0"
llm = ChatOllama(temperature=0, model=model)

output_parser = StrOutputParser()

chain = (
    {x: itemgetter(x) for x in ["noticia"]}
    | prompt
    | llm
    | output_parser
)

sentimientos = []
for noticia in contents:
  #print(chain.invoke({"noticia": noticia}))
  sentimientos.append(chain.invoke({"noticia": noticia}))
newsFeelings = pd.DataFrame({
    "Noticia": noticia,
    "sentimientos": sentimientos
})
newsFeelings.head()

# transformamos la lista de cadenas que extraemos del dataframe anterior, en una lista comun, para su posterior analisis
lista_sentimientos  = [elemento.strip() for cadena in sentimientos for elemento in cadena.split(',')]

print(lista_sentimientos)

# Procedemos a graficar la lista de sentimientos

import matplotlib.pyplot as plt
from collections import Counter
contador_sentimientos = Counter(lista_sentimientos)

# Convertir el contador a un DataFrame
df_sentimientos = pd.DataFrame(contador_sentimientos.items(), columns=['Sentimiento', 'Frecuencia'])

# Ordenar el DataFrame por frecuencia descendente
df_sentimientos = df_sentimientos.sort_values(by='Frecuencia', ascending=False)
sns.set(style="whitegrid")

# Crear el gráfico de barras
plt.figure(figsize=(12, 8))
barplot = sns.barplot(
    x='Sentimiento',
    y='Frecuencia',
    data=df_sentimientos,
    palette='viridis',  # Mapa de colores
    edgecolor='black'
)

# Añadir etiquetas con los valores encima de las barras
for p in barplot.patches:
    barplot.annotate(
        format(p.get_height(), '.0f'),
        (p.get_x() + p.get_width() / 2., p.get_height()),
        ha = 'center',
        va = 'center',
        xytext = (0, 10),  # Desplazamiento vertical de la etiqueta
        textcoords = 'offset points',
        fontsize=10,
        color='black'
    )

# Estilizar ejes y títulos
plt.xlabel('Sentimientos', fontsize=14)
plt.ylabel('Frecuencia', fontsize=14)
plt.title('Frecuencia de Sentimientos (Diagrama de Barras)', fontsize=16, fontweight='bold')
plt.xticks(rotation=45, ha='right')
plt.grid(True, linestyle='--', alpha=0.7)

# Mostrar la gráfica
plt.show()

"""A partir de la grafica, se puede analizar que la ciudad esta experimentando un auge economico, turisitco y social, debido a que los principales sentimientos que evoca la ciudad son realmente positivos, **Optimismo**, **Exitacion** y **Anticipacion**.

el sentimiento mas importante acerca de la ciudad  el **Optimismo**, lo cual significa que las personas confian en que las cosas seguiran mejorando y habran mas y mejores oportunidades de crecimiento para la poblacion y buenas experiencias para los turistas. **Excitacion** es otro de los grandes sentimientos, se puede entender que los turistas potenciales y demas poblacion, siente emocion, por conocer la belleza del lugar y crear hermosos recuerdos alli.

**Anticipacion** es otro de estos importantes sentimientos, podemos inferir que las autoridades estan tomando medidas para poder atender a la creciente cantidad de turistas que cada año visitan la ciudad, con el fin facilitar su ingreso, estadia y seguridad durante su periodo vacaional

esta informacion aunque util, hace parte de un primer grupo de analisis, que pueden dar una luz sobre la viabilidad de inversion en el sector turismo de la ciudad, este reporte da un parte positivo, teniendo en cuenta las recientes emergencias medioambientales que ha sufrido la ciudad debido a catastrofes naturales como huracanes, los cuales han perjudicado seriamente el turismo en la ciudad, como a su poblacion raizal
"""